### ISSUE TITLE
Keys wrongfully displayed when using `-H` and `-L` together

### ISSUE THREAD

**Issue by rdbo** [jjsullivan5196/wvkbd#58] opened 2023-12-26 17:39 UTC
wvkbd version: wvkbd-0.14.3
Compositor: river 0.2.6

I am running the following command: `$ wvkbd-mobintl -H 400 -L 400`

Initially, everything is looks fine:
![image](https://github.com/jjsullivan5196/wvkbd/assets/57117082/13308db5-86b4-4bf9-bfa4-5da10eb5e293)

But then, when I try to press keys, I can notice that they are wrongfully placed (I tried to press X, C, V, ask you can see below. And they re-render in the right place):
![image](https://github.com/jjsullivan5196/wvkbd/assets/57117082/abd1dff4-cfdc-402e-aa75-dcabaa2ca1ff)

I also noticed that it might be showing the wrong keyboard layout. Because when I press shift (located at around the position of the Z key), it shows another layout:
![image](https://github.com/jjsullivan5196/wvkbd/assets/57117082/da8b4752-6695-46c0-85ac-878b00988659)

If I use only `-L` instead of `-L` and `-H`, it works fine:
![image](https://github.com/jjsullivan5196/wvkbd/assets/57117082/de8f9bf6-3741-4daa-9edc-33f62f90edc7)

**Comment by proycon** [comment] 2024-03-03 10:45
Sorry for the delay. didn't notice this issue before. I tried to reproduce this on both Hyprland and wayfire with the latest wvkbd git version and at least there I can't reproduce it. I wonder if the issue got resolved in the meantime or if it's specific to river.

**Closed** 2024-03-25 12:04 UTC
