### ISSUE TITLE
Segfault when starting hidden

### ISSUE THREAD

**Issue by rexy712** [jjsullivan5196/wvkbd#23] opened 2022-03-12 20:01 UTC
_I get a segfault whenever I try to start the keyboard hidden on sway v1.7.  main.c line 535 is where it happens. I managed to work around this but it feels like a hackjob.
```
diff --git a/main.c b/main.c
index 5eab410..81f9ea3 100644
--- a/main.c
+++ b/main.c
@@ -531,6 +531,9 @@ main(int argc, char **argv) {
        signal(SIGUSR1, hide);
        signal(SIGUSR2, show);
 
+       while (run_display && !layer_surface) {
+               sleep(1);
+       }
        while (run_display) {
                while (wl_display_dispatch(display) != -1 && layer_surface) {
                }

```_

**Comment by proycon** [comment] 2022-06-13 20:56
This suggests you get the segfault immediate on start? I can't reproduce this on the latest master branch of wvkbd with sway 1.7-5f1f34bd3f (in sxmo on pinephone), so I wonder if it got resolved in the meantime. Do you still experience it?

**Comment by proycon** [comment] 2022-06-13 22:06
I can reproduce it now after a tip on our irc channel; it occurs only in landscape mode.

**Comment by proycon** [comment] 2022-06-13 22:13
Fixed now

**Closed** 2022-06-13 22:13 UTC
